import Head from "next/head";
import Image from "next/image";
import Login from "@/components/form/Login";

export default function Home() {
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Login />
    </>
  );
}
