import Head from "next/head";
import Image from "next/image";
import Navbar from "@/components/header/Navbar";
import ListProducts from "@/components/products/ListProducts";

export default function Home() {
  return (
    <>
      <Head>
        <title>E-Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <Navbar />
      <ListProducts />
    </>
  );
}
