import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import Top from "@/components/header/Top";
import Header from "@/components/header/Header";
import Navbar from "@/components/header/Navbar";
import TopRated from "@/components/products/TopRated";
import Carousel from "@/components/carousel/Carousel";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>E-Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
      </Head>
      <main>
        <Top />
        <Header />
        <Navbar />
        <Footer />
        <div className="w-fit h-fit mx-auto my-40 bg-custom-3">
          <Link href="/auth/login" className="text-[128px]">
            LOGIN
          </Link>
        </div>
        <Carousel />
        <TopRated />
      </main>
    </>
  );
}
